spring.datasource.url=jdbc:postgresql://localhost:5432/booklend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=booklend
spring.datasource.password=booklend

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never

spring.h2.console.enabled=false

booklend.persistence=postgres
